services:
  manager:
    build: ./manager
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=ollama/llama3.2:latest
      - CREWAI_DISABLE_TELEMETRY=true
      - OTEL_SDK_DISABLED=true
    depends_on:
      - crew_pesquisa
      - crew_redacao
      - crew_avaliacao

  crew_pesquisa:
    build: ./crew_pesquisa
    ports:
      - "8001:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=ollama/llama3.2:latest
      - CREWAI_DISABLE_TELEMETRY=true
      - OTEL_SDK_DISABLED=true

  crew_redacao:
    build: ./crew_redacao
    ports:
      - "8002:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=ollama/llama3.2:latest
      - CREWAI_DISABLE_TELEMETRY=true
      - OTEL_SDK_DISABLED=true

  crew_avaliacao:
    build: ./crew_avaliacao
    ports:
      - "8003:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=ollama/llama3.2:latest
      - CREWAI_DISABLE_TELEMETRY=true
      - OTEL_SDK_DISABLED=true
      
  chat_streamlit:
    build: ./chat_streamlit
    ports:
      - "8501:8501"
    environment:
      - MANAGER_URL=http://manager:8000
    depends_on:
      - manager
